### ISSUE TITLE
external-dns keep complaining googleapi: Error 403: Forbidden, forbidden

### ISSUE THREAD

**Issue by huweiATgithub** [gitpod-io/gitpod-gke-guide#11]
### Bug description

I tried:
- restart the pod
- recreating serviceAccount and regenerating serviceAccount json credentials
None of this works.

It may relate to the issue here: 
https://github.com/kubernetes-sigs/external-dns/issues/509

I did a lot of searches, none of those worked.

Maybe only the workload identity approach would work, not try yet.

### Steps to reproduce

run make install

**Comment by MrSimonEmms** [comment]
@huweiATgithub Some upgrades were made to this installer since this issue was raised. Can you run again and check please?

If still an issue, can you provide the configuration entered in your `.env` file (redacting anything sensitive) for us to recreate?
