### ISSUE TITLE
why not using terraform?

### ISSUE THREAD

**Issue by ionutale** [gitpod-io/gitpod-gke-guide#17]
this is just a question

**Comment by aledbf** [comment]
[I am going to borrow the comment from the EKS guide
](https://github.com/gitpod-io/gitpod-eks-guide/issues/17)
Closing. The official CLI for GCP is `gcloud`.

The guide's goal is to install Gitpod in GKE, not to prescribe how to provision the cluster.
Now that we are switching to a go installer, after rendering the manifests feel free to use the tool of choice.
