### ISSUE TITLE
If pre-emptible=false, `make install` fails

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod-gke-guide#6]
### Bug description

Pre-emptible instance configuration appears to be misconfigured when set to false

### Steps to reproduce

Set `PREEMPTIBLE=false` or `PREEMPTIBLE=` in the `.env` and run `main install`

**Comment by elsenorbw** [comment]
Yep, just looking at the same thing. 
Tried to fix it with unset but that breaks the nodepool creation as they've used quotes around that..
